apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    environment: {{ .Values.environment | default "dev" }}
    managed-by: {{ .Values.namespace.managedBy | default "gitops" }}
