apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docbridge
  namespace: argocd
spec:
  project: docbridge-project
  source:
    repoURL: 'https://github.com/Docbridge-devops-project/Docbridge-kubernetes.git'
    targetRevision: main
    path: helm/docbridge
    helm:
      valueFiles:
        - values.yaml
        - values.dev.yaml
      parameters:
        - name: azure.keyVaultName
          value: docbridge-dev-kv
        - name: azure.workloadIdentityClientId
          value: "c0fd539f-5d5e-411a-aef4-29c44997a94d"
        - name: azure.tenantId
          value: "ffdb5413-63c8-40ec-a158-c5ad34880e3d"
        - name: database.host
          value: docbridge-dev-postgres-c.postgres.database.azure.com
        - name: gateway.corsOrigin
          value: "http://135.233.62.51"
        - name: image.tag
          value: "0f0907b"
        - name: global.imageTag
          value: "0f0907b"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
