apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: docbridge-project
  namespace: argocd
spec:
  description: "DocBridge AppProject for Capstone GitOps deployment"
  sourceRepos:
    - '*'
  destinations:
    - namespace: production
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
